function home(){const bestsellers=['glow-table-lamp','zen-vase','cozy-plaid','warmth-candle'].map(id=>products.find(p=>p.id===id)).filter(Boolean);return \`
<section class="home-hero">
  <div class="shell home-hero-inner">
    <div class="home-hero-copy">
      <span class="eyebrow">Sfeervol wonen begint bij GlowNest</span>
      <h1>Maak van je huis <span>jouw warme nest</span></h1>
      <p>Sfeervolle verlichting, stijlvolle decoratie en comfort die bij jou past.</p>
      <a class="btn btn-accent home-hero-cta" href="/search?q=popular" data-link>Ontdek de collectie <span aria-hidden="true">→</span></a>
    </div>
  </div>
</section>
<section class="benefits home-benefits">
  <div class="shell benefit-grid">
    <div class="benefit"><span class="benefit-icon" aria-hidden="true">🚚</span><div><strong>Gratis verzending</strong><span>vanaf €49,95</span></div></div>
    <div class="benefit"><span class="benefit-icon" aria-hidden="true">↶</span><div><strong>30 dagen bedenktijd</strong><span>niet tevreden, geld terug</span></div></div>
    <div class="benefit"><span class="benefit-icon" aria-hidden="true">♢</span><div><strong>Veilig betalen</strong><span>iDEAL, Klarna & meer</span></div></div>
    <div class="benefit"><span class="benefit-icon" aria-hidden="true">◖◗</span><div><strong>Persoonlijke service</strong><span>we helpen je graag</span></div></div>
  </div>
</section>
<section class="home-section">
  <div class="shell">
    <div class="home-section-head">
      <h2>Shop je ruimte</h2>
      <a class="home-view-all" href="/search" data-link>Bekijk alle categorieën <span aria-hidden="true">→</span></a>
    </div>
    <div class="category-grid home-category-grid">\${Object.keys(categories).map(categoryCard).join('')}</div>
  </div>
</section>
<section class="home-section home-showcase-section" id="reviews">
  <div class="shell home-showcase">
    <div class="home-bestsellers">
      <div class="home-section-head"><h2>Bestsellers</h2><a class="home-view-all" href="/search?q=popular" data-link>Bekijk alles <span aria-hidden="true">→</span></a></div>
      <div class="product-grid home-product-grid">\${bestsellers.map(productCard).join('')}</div>
    </div>
    <div class="home-reviews">
      <div class="home-section-head"><h2>Wat klanten zeggen</h2><a class="home-view-all" href="/about" data-link>Alle reviews <span aria-hidden="true">→</span></a></div>
      <div class="review-grid home-review-grid">\${reviews.map(r=>\`<article class="review-card"><div class="stars">\${stars(r.rating)}</div><p>“\${r.text}”</p><strong>– \${r.name}</strong></article>\`).join('')}</div>
    </div>
  </div>
</section>\`}

function categoryPage(slug){const c=categories[slug];if(!c)return notFound();const list=products.filter(p=>p.category===slug);return `<section class="page-hero"><div class="shell"><div class="breadcrumbs"><a href="/" data-link>Home</a> / ${c.name}</div><h1>${c.name}</h1><p>${c.intro}</p></div></section><section class="section"><div class="shell category-layout"><aside class="filters"><h3>Filteren</h3><div class="filter-group"><strong>Prijs</strong><label><input type="checkbox" data-price="25"> Onder €25</label><label><input type="checkbox" data-price="50"> Onder €50</label><label><input type="checkbox" data-price="80"> Onder €80</label></div><div class="filter-group"><label for="sort"><strong>Sorteren</strong></label><select id="sort"><option value="featured">Aanbevolen</option><option value="low">Prijs laag-hoog</option><option value="high">Prijs hoog-laag</option><option value="rating">Best beoordeeld</option></select></div></aside><div><div class="category-toolbar"><strong>${c.name}</strong><span class="result-count" id="result-count">${list.length} producten</span></div><div class="product-grid" id="category-products">${list.map(productCard).join('')}</div></div></div></section>`}

function productPage(id){const p=products.find(x=>x.id===id);if(!p)return notFound();const related=products.filter(x=>x.category===p.category&&x.id!==p.id).slice(0,4);return `<section class="product-page"><div class="shell"><div class="breadcrumbs"><a href="/" data-link>Home</a> / <a href="/category/${p.category}" data-link>${categories[p.category].name}</a> / ${p.name}</div><div class="product-layout"><div class="product-gallery"><div class="main-image"><img src="${p.image}" alt="${p.name}"></div></div><div class="product-detail"><span class="eyebrow">${categories[p.category].name}</span><h1>${p.name}</h1><div class="rating">★ ${p.rating} · ${p.reviews} reviews</div><p class="lead">${p.desc}</p><div class="big-price">${money.format(p.price)}</div><span class="stock">Op voorraad</span><div class="buy-row"><button class="btn btn-dark" data-add="${p.id}">In winkelwagen</button><button class="btn btn-soft" data-wish="${p.id}">${state.wishlist.includes(p.id)?'♥ Favoriet':'♡ Bewaren'}</button></div><div class="feature-list">${p.specs.map(s=>`<div>✓ ${s}</div>`).join('')}</div><div class="accordion"><details open><summary>Productinformatie</summary><p>${p.desc}</p></details><details><summary>Verzending &amp; retour</summary><p>Gratis verzending vanaf €49,95. Anders €4,95. Je hebt 30 dagen om ongebruikte producten te retourneren.</p></details><details><summary>Materialen &amp; onderhoud</summary><p>${p.specs.join(' · ')}. Volg altijd de meegeleverde onderhoudsinstructies.</p></details></div></div></div></div></section><section class="section"><div class="shell"><div class="section-head"><div><h2>Reviews</h2><p>Ervaringen van klanten met dit product.</p></div></div><div class="review-summary"><div><div class="stars">${stars(p.rating)}</div><strong>${p.rating} / 5</strong></div><p class="muted">Gebaseerd op ${p.reviews} beoordelingen. Klanten noemen vooral de rustige uitstraling, prijs en makkelijke plaatsing.</p></div></div></section>${related.length?`<section class="section-tight"><div class="shell"><div class="section-head"><h2>Past hier goed bij</h2></div><div class="product-grid">${related.map(productCard).join('')}</div></div></section>`:''}`}

function searchPage(query=''){const q=query.toLowerCase().trim();let list=products;if(q&&q!=='popular') list=products.filter(p=>[p.name,p.short,p.desc,...p.tags,categories[p.category].name].join(' ').toLowerCase().includes(q));return `<section class="page-hero"><div class="shell"><div class="breadcrumbs"><a href="/" data-link>Home</a> / Zoeken</div><h1>${q&&q!=='popular'?`Zoeken naar “${escapeHtml(q)}”`:'Alle producten'}</h1><p>${list.length} resultaten gevonden.</p></div></section><section class="section"><div class="shell">${list.length?`<div class="product-grid">${list.map(productCard).join('')}</div>`:`<div class="empty-state"><h2>Niets gevonden</h2><p>Probeer bijvoorbeeld “lamp”, “gaming”, “kaars” of “plant”.</p><a class="btn btn-dark" href="/" data-link>Terug naar home</a></div>`}</div></section>`}

function wishlistPage(){const list=products.filter(p=>state.wishlist.includes(p.id));return `<section class="page-hero"><div class="shell"><h1>Favorieten</h1><p>Producten die je even wilde bewaren.</p></div></section><section class="section"><div class="shell">${list.length?`<div class="product-grid">${list.map(productCard).join('')}</div>`:`<div class="empty-state"><h2>Nog geen favorieten</h2><p>Bewaar producten met het hartje en ze verschijnen hier.</p><a class="btn btn-dark" href="/" data-link>Shop verder</a></div>`}</div></section>`}

function cartItems(){return Object.entries(state.cart).map(([id,qty])=>({p:products.find(x=>x.id===id),qty})).filter(x=>x.p)}
function totals(){const sub=cartItems().reduce((s,{p,qty})=>s+p.price*qty,0);const shipping=sub===0?0:sub>=49.95?0:4.95;return{sub,shipping,total:sub+shipping}}
function cartPage(){const items=cartItems(),t=totals();if(!items.length)return `<section class="cart-page"><div class="shell empty-state"><h2>Je winkelwagen is nog leeg</h2><p>Kies iets warms. Een kamer gaat zichzelf helaas niet gezellig maken.</p><a class="btn btn-dark" href="/" data-link>Shop producten</a></div></section>`;return `<section class="cart-page"><div class="shell"><div class="breadcrumbs"><a href="/" data-link>Home</a> / Winkelwagen</div><h1>Winkelwagen</h1><div class="cart-layout"><div>${items.map(({p,qty})=>`<article class="cart-item"><a href="/product/${p.id}" data-link><img src="${p.image}" alt="${p.name}"></a><div><h3><a href="/product/${p.id}" data-link>${p.name}</a></h3><p>${p.short}</p><div class="qty-row"><button data-qty="${p.id}" data-delta="-1" aria-label="Minder">−</button><strong>${qty}</strong><button data-qty="${p.id}" data-delta="1" aria-label="Meer">+</button><button class="remove-link" data-remove="${p.id}">Verwijderen</button></div></div><strong>${money.format(p.price*qty)}</strong></article>`).join('')}</div><aside class="summary-card"><h2>Overzicht</h2><div class="summary-line"><span>Subtotaal</span><strong>${money.format(t.sub)}</strong></div><div class="summary-line"><span>Verzending</span><strong>${t.shipping?money.format(t.shipping):'Gratis'}</strong></div><div class="summary-line summary-total"><span>Totaal</span><span>${money.format(t.total)}</span></div><a class="btn btn-accent" href="/checkout" data-link>Doorgaan naar afrekenen</a><p class="small muted">Dit is een demo. Er wordt geen echte betaling uitgevoerd.</p></aside></div></div></section>`}

function checkoutPage(){const items=cartItems(),t=totals();if(!items.length)return cartPage();return `<section class="checkout"><div class="shell"><div class="breadcrumbs"><a href="/cart" data-link>Winkelwagen</a> / Afrekenen</div><h1>Afrekenen</h1><form id="checkout-form" class="checkout-layout"><div><section class="form-card"><h2>Contact &amp; bezorging</h2><div class="form-grid"><div class="field"><label>Voornaam</label><input name="firstName" required autocomplete="given-name"></div><div class="field"><label>Achternaam</label><input name="lastName" required autocomplete="family-name"></div><div class="field full"><label>E-mailadres</label><input name="email" type="email" required autocomplete="email"></div><div class="field full"><label>Adres</label><input name="address" required autocomplete="street-address"></div><div class="field"><label>Postcode</label><input name="postal" required pattern="[0-9]{4}\s?[A-Za-z]{2}" placeholder="1234 AB"></div><div class="field"><label>Plaats</label><input name="city" required autocomplete="address-level2"></div></div></section><section class="form-card"><h2>Betaalmethode</h2><div class="pay-options"><label class="pay-option"><input type="radio" name="payment" value="iDEAL" required> iDEAL <span class="muted small">(simulatie)</span></label><label class="pay-option"><input type="radio" name="payment" value="Klarna"> Klarna <span class="muted small">(simulatie)</span></label><label class="pay-option"><input type="radio" name="payment" value="Kaart"> Creditcard <span class="muted small">(simulatie)</span></label></div></section></div><aside class="summary-card"><h2>Jouw bestelling</h2>${items.map(({p,qty})=>`<div class="summary-line"><span>${qty}× ${p.name}</span><strong>${money.format(p.price*qty)}</strong></div>`).join('')}<div class="summary-line"><span>Verzending</span><strong>${t.shipping?money.format(t.shipping):'Gratis'}</strong></div><div class="summary-line summary-total"><span>Totaal</span><span>${money.format(t.total)}</span></div><button class="btn btn-accent" type="submit">Bestelling plaatsen</button><p class="small muted">Er wordt niets afgeschreven. Deze checkout is alleen voor de demo.</p></aside></form></div></section>`}

function confirmationPage(){const data=JSON.parse(sessionStorage.getItem('glownest-order')||'null');if(!data)return `<section class="order-confirm"><div class="shell"><div class="checkmark">✓</div><h1>Bestelling afgerond</h1><p>Je demo-bestelling is afgerond.</p><a class="btn btn-dark" href="/" data-link>Terug naar home</a></div></section>`;return `<section class="order-confirm"><div class="shell"><div class="checkmark">✓</div><span class="eyebrow">Bedankt ${escapeHtml(data.name)}</span><h1>Bestelling afgerond</h1><p>Bestelnummer <strong>${data.order}</strong>. In een echte webshop zou nu een bevestiging naar <strong>${escapeHtml(data.email)}</strong> worden gestuurd.</p><p>Totaal: <strong>${money.format(data.total)}</strong> · Betaalmethode: ${escapeHtml(data.payment)}</p><a class="btn btn-dark" href="/" data-link>Terug naar GlowNest</a></div></section>`}